spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  thymeleaf:
    cache: false

server:
  port: 8888
  servlet:
    context-path: /hotel

logging:
  level:
    com.hadron.hotelmanage: trace
  file: E:\logs\hotel.log
